import 'package:flutter_test/flutter_test.dart';
import 'package:fpdart/fpdart.dart';
import 'package:mockito/annotations.dart';
import 'package:mockito/mockito.dart';
import 'package:nightmail/core/error/failures.dart';
import 'package:nightmail/domain/entities/calendar_event.dart';
import 'package:nightmail/domain/usecases/get_calendar_events.dart';
import 'package:nightmail/presentation/blocs/calendar/calendar_bloc.dart';
import 'package:nightmail/presentation/blocs/calendar/calendar_event.dart';
import 'package:nightmail/presentation/blocs/calendar/calendar_state.dart';

import 'calendar_bloc_test.mocks.dart';

// fpdart's Either is not auto-generated by mockito, so register a dummy.
final _emptyRight = Right<Failure, List<CalendarEvent>>([]);

final _tMonday = DateTime(2026, 6, 9); // known Monday

final _tEvents = <CalendarEvent>[
  CalendarEvent(
    id: 'e1',
    subject: 'Stand-up',
    start: DateTime.utc(2026, 6, 10, 9, 0),
    end: DateTime.utc(2026, 6, 10, 9, 15),
    isAllDay: false,
  ),
];

@GenerateMocks([GetCalendarEvents])
void main() {
  late MockGetCalendarEvents mockGetCalendarEvents;

  setUp(() {
    mockGetCalendarEvents = MockGetCalendarEvents();
    provideDummy<Either<Failure, List<CalendarEvent>>>(_emptyRight);
  });

  group('CalendarBloc', () {
    test('initial state has weekStart set to current Monday', () {
      final bloc = CalendarBloc(getCalendarEvents: mockGetCalendarEvents);
      expect(bloc.state, isA<CalendarInitial>());
      expect(bloc.state.weekStart.weekday, 1);
      bloc.close();
    });

    test('emits [CalendarLoading, CalendarLoaded] on successful fetch',
        () async {
      when(mockGetCalendarEvents(any))
          .thenAnswer((_) async => Right(_tEvents));

      final bloc = CalendarBloc(getCalendarEvents: mockGetCalendarEvents);
      final states = <CalendarState>[];
      final sub = bloc.stream.listen(states.add);

      bloc.add(CalendarWeekLoadRequested(weekStart: _tMonday));
      await bloc.stream
          .firstWhere((s) => s is CalendarLoaded || s is CalendarError);
      await sub.cancel();
      await bloc.close();

      expect(states[0], isA<CalendarLoading>());
      expect(states[0].weekStart, _tMonday);
      expect(states[1], isA<CalendarLoaded>());
      expect((states[1] as CalendarLoaded).events.length, 1);
    });

    test('emits [CalendarLoading, CalendarError] on failure', () async {
      when(mockGetCalendarEvents(any)).thenAnswer(
        (_) async =>
            const Left(ServerFailure(message: 'Calendar unavailable')),
      );

      final bloc = CalendarBloc(getCalendarEvents: mockGetCalendarEvents);
      final states = <CalendarState>[];
      final sub = bloc.stream.listen(states.add);

      bloc.add(CalendarWeekLoadRequested(weekStart: _tMonday));
      await bloc.stream
          .firstWhere((s) => s is CalendarLoaded || s is CalendarError);
      await sub.cancel();
      await bloc.close();

      expect(states[0], isA<CalendarLoading>());
      expect(states[1], isA<CalendarError>());
      expect((states[1] as CalendarError).message, 'Calendar unavailable');
    });

    test('emits [CalendarLoading, CalendarLoaded] on week navigation',
        () async {
      when(mockGetCalendarEvents(any))
          .thenAnswer((_) async => Right(_tEvents));

      final bloc = CalendarBloc(getCalendarEvents: mockGetCalendarEvents);
      final states = <CalendarState>[];
      final sub = bloc.stream.listen(states.add);

      bloc.add(CalendarWeekNavigated(weekStart: _tMonday));
      await bloc.stream
          .firstWhere((s) => s is CalendarLoaded || s is CalendarError);
      await sub.cancel();
      await bloc.close();

      expect(states[0], isA<CalendarLoading>());
      expect(states[1], isA<CalendarLoaded>());
      expect((states[1] as CalendarLoaded).events, _tEvents);
    });

    test('passes a 7-day UTC date range to use case', () async {
      when(mockGetCalendarEvents(any))
          .thenAnswer((_) async => Right(_tEvents));

      final bloc = CalendarBloc(getCalendarEvents: mockGetCalendarEvents);
      bloc.add(CalendarWeekLoadRequested(weekStart: _tMonday));
      await bloc.stream
          .firstWhere((s) => s is CalendarLoaded || s is CalendarError);
      await bloc.close();

      final captured =
          verify(mockGetCalendarEvents(captureAny)).captured;
      final params = captured.first as GetCalendarEventsParams;
      expect(params.startDateTime.isUtc, isTrue);
      expect(params.endDateTime.difference(params.startDateTime).inDays, 7);
    });
  });
}
