import 'package:flutter/services.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:fpdart/fpdart.dart';
import 'package:mockito/annotations.dart';
import 'package:mockito/mockito.dart';
import 'package:nightmail/core/error/failures.dart';
import 'package:nightmail/domain/entities/calendar_event.dart';
import 'package:nightmail/domain/usecases/cancel_calendar_event.dart';
import 'package:nightmail/domain/usecases/decline_calendar_event.dart';
import 'package:nightmail/domain/usecases/get_cached_calendar_events.dart';
import 'package:nightmail/domain/usecases/get_calendar_events.dart';
import 'package:nightmail/domain/usecases/propose_new_time.dart';
import 'package:nightmail/domain/usecases/update_calendar_event.dart';
import 'package:nightmail/infrastructure/accounts/account.dart';
import 'package:nightmail/infrastructure/accounts/account_manager.dart';
import 'package:nightmail/infrastructure/notifications/notification_service.dart';
import 'package:nightmail/presentation/blocs/calendar/calendar_bloc.dart';
import 'package:nightmail/presentation/blocs/calendar/calendar_event.dart';
import 'package:nightmail/presentation/blocs/calendar/calendar_state.dart';

import 'calendar_bloc_test.mocks.dart';

// fpdart's Either is not auto-generated by mockito, so register a dummy.
final _emptyRight = Right<Failure, List<CalendarEvent>>([]);
final _voidRight = Right<Failure, void>(null);

final _tMonday = DateTime(2026, 6, 9); // known Monday

final _tEvents = <CalendarEvent>[
  CalendarEvent(
    id: 'e1',
    subject: 'Stand-up',
    start: DateTime.utc(2026, 6, 10, 9, 0),
    end: DateTime.utc(2026, 6, 10, 9, 15),
    isAllDay: false,
  ),
];

@GenerateMocks([
  GetCalendarEvents,
  GetCachedCalendarEvents,
  CancelCalendarEvent,
  CancelCalendarEventSeries,
  DeclineCalendarEvent,
  ProposeNewTime,
  UpdateCalendarEvent,
  NotificationService,
  AccountManager,
])
void main() {
  TestWidgetsFlutterBinding.ensureInitialized();

  late MockGetCalendarEvents mockGetCalendarEvents;
  late MockGetCachedCalendarEvents mockGetCachedCalendarEvents;
  late MockCancelCalendarEvent mockCancelCalendarEvent;
  late MockCancelCalendarEventSeries mockCancelCalendarEventSeries;
  late MockDeclineCalendarEvent mockDeclineCalendarEvent;
  late MockProposeNewTime mockProposeNewTime;
  late MockUpdateCalendarEvent mockUpdateCalendarEvent;
  late MockNotificationService mockNotificationService;
  late MockAccountManager mockAccountManager;

  CalendarBloc makeBloc() => CalendarBloc(
        getCalendarEvents: mockGetCalendarEvents,
        getCachedCalendarEvents: mockGetCachedCalendarEvents,
        cancelCalendarEvent: mockCancelCalendarEvent,
        cancelCalendarEventSeries: mockCancelCalendarEventSeries,
        declineCalendarEvent: mockDeclineCalendarEvent,
        proposeNewTime: mockProposeNewTime,
        updateCalendarEvent: mockUpdateCalendarEvent,
        notificationService: mockNotificationService,
        accountManager: mockAccountManager,
      );

  setUp(() {
    mockGetCalendarEvents = MockGetCalendarEvents();
    mockGetCachedCalendarEvents = MockGetCachedCalendarEvents();
    mockCancelCalendarEvent = MockCancelCalendarEvent();
    mockCancelCalendarEventSeries = MockCancelCalendarEventSeries();
    mockDeclineCalendarEvent = MockDeclineCalendarEvent();
    mockProposeNewTime = MockProposeNewTime();
    mockUpdateCalendarEvent = MockUpdateCalendarEvent();
    mockNotificationService = MockNotificationService();
    mockAccountManager = MockAccountManager();
    when(mockAccountManager.activeAccount).thenReturn(const GmailAccount(
      id: 'acct1',
      displayName: 'Test',
      emailAddress: 'test@example.com',
    ));
    when(mockNotificationService.cancelEventReminder(
      accountId: anyNamed('accountId'),
      eventId: anyNamed('eventId'),
    )).thenAnswer((_) async {});
    when(mockNotificationService.scheduleEventReminder(
      accountId: anyNamed('accountId'),
      eventId: anyNamed('eventId'),
      eventTitle: anyNamed('eventTitle'),
      startUtc: anyNamed('startUtc'),
      reminderMinutes: anyNamed('reminderMinutes'),
      startIso: anyNamed('startIso'),
    )).thenAnswer((_) async {});
    TestDefaultBinaryMessengerBinding.instance.defaultBinaryMessenger
        .setMockMethodCallHandler(
      const MethodChannel('au.com.sharpblue.nightmail/calendar_refresh'),
      (_) async => null,
    );
    provideDummy<Either<Failure, List<CalendarEvent>>>(_emptyRight);
    provideDummy<Either<Failure, void>>(_voidRight);
    // Default: an empty cache, so the tests written against the network-first
    // flow still see [CalendarLoading] before their result. Registered after
    // provideDummy, which mockito needs in place before an fpdart-returning
    // method is stubbed.
    when(mockGetCachedCalendarEvents(any))
        .thenAnswer((_) async => Right(<CalendarEvent>[]));
  });

  group('CalendarBloc', () {
    test('initial state has weekStart set to current Monday', () {
      final bloc = makeBloc();
      expect(bloc.state, isA<CalendarInitial>());
      expect(bloc.state.weekStart.weekday, 1);
      bloc.close();
    });

    test('emits [CalendarLoading, CalendarLoaded] on successful fetch',
        () async {
      when(mockGetCalendarEvents(any))
          .thenAnswer((_) async => Right(_tEvents));

      final bloc = makeBloc();
      final states = <CalendarState>[];
      final sub = bloc.stream.listen(states.add);

      bloc.add(CalendarWeekLoadRequested(weekStart: _tMonday));
      await bloc.stream
          .firstWhere((s) => s is CalendarLoaded || s is CalendarError);
      await sub.cancel();
      await bloc.close();

      expect(states[0], isA<CalendarLoading>());
      expect(states[0].weekStart, _tMonday);
      expect(states[1], isA<CalendarLoaded>());
      expect((states[1] as CalendarLoaded).events.length, 1);
    });

    test('emits [CalendarLoading, CalendarError] on failure', () async {
      when(mockGetCalendarEvents(any)).thenAnswer(
        (_) async =>
            const Left(ServerFailure(message: 'Calendar unavailable')),
      );

      final bloc = makeBloc();
      final states = <CalendarState>[];
      final sub = bloc.stream.listen(states.add);

      bloc.add(CalendarWeekLoadRequested(weekStart: _tMonday));
      await bloc.stream
          .firstWhere((s) => s is CalendarLoaded || s is CalendarError);
      await sub.cancel();
      await bloc.close();

      expect(states[0], isA<CalendarLoading>());
      expect(states[1], isA<CalendarError>());
      expect((states[1] as CalendarError).message, 'Calendar unavailable');
    });

    test('emits [CalendarLoading, CalendarLoaded] on week navigation',
        () async {
      when(mockGetCalendarEvents(any))
          .thenAnswer((_) async => Right(_tEvents));

      final bloc = makeBloc();
      final states = <CalendarState>[];
      final sub = bloc.stream.listen(states.add);

      bloc.add(CalendarWeekNavigated(weekStart: _tMonday));
      await bloc.stream
          .firstWhere((s) => s is CalendarLoaded || s is CalendarError);
      await sub.cancel();
      await bloc.close();

      expect(states[0], isA<CalendarLoading>());
      expect(states[1], isA<CalendarLoaded>());
      expect((states[1] as CalendarLoaded).events, _tEvents);
    });

    test('passes a 7-day UTC date range to use case', () async {
      when(mockGetCalendarEvents(any))
          .thenAnswer((_) async => Right(_tEvents));

      final bloc = makeBloc();
      bloc.add(CalendarWeekLoadRequested(weekStart: _tMonday));
      await bloc.stream
          .firstWhere((s) => s is CalendarLoaded || s is CalendarError);
      await bloc.close();

      final captured =
          verify(mockGetCalendarEvents(captureAny)).captured;
      final params = captured.first as GetCalendarEventsParams;
      expect(params.startDateTime.isUtc, isTrue);
      expect(params.endDateTime.difference(params.startDateTime).inDays, 7);
    });

    test('cancel reloads week on success', () async {
      when(mockCancelCalendarEvent(any))
          .thenAnswer((_) async => Right(null));
      when(mockGetCalendarEvents(any))
          .thenAnswer((_) async => Right(_tEvents));

      final bloc = makeBloc();
      bloc.add(const CalendarEventCancelRequested(eventId: 'e1'));
      await bloc.stream
          .firstWhere((s) => s is CalendarLoaded || s is CalendarError);
      await bloc.close();

      verify(mockCancelCalendarEvent(
        const CancelCalendarEventParams(eventId: 'e1'),
      )).called(1);
      verify(mockGetCalendarEvents(any)).called(1);
    });

    test('cancel still reloads the week when no window relay exists', () async {
      // Linux, Android and iOS have no native calendar_refresh handler at all,
      // so notifyEventSaved is a MissingPluginException there. Clearing the
      // mock reproduces that. An uncaught throw would skip the reload.
      TestDefaultBinaryMessengerBinding.instance.defaultBinaryMessenger
          .setMockMethodCallHandler(
        const MethodChannel('au.com.sharpblue.nightmail/calendar_refresh'),
        null,
      );
      when(mockCancelCalendarEvent(any))
          .thenAnswer((_) async => Right(null));
      when(mockGetCalendarEvents(any))
          .thenAnswer((_) async => Right(_tEvents));

      final bloc = makeBloc();
      bloc.add(const CalendarEventCancelRequested(eventId: 'e1'));
      await bloc.stream
          .firstWhere((s) => s is CalendarLoaded || s is CalendarError);
      await bloc.close();

      verify(mockGetCalendarEvents(any)).called(1);
    });

    test('decline reloads week on success', () async {
      when(mockDeclineCalendarEvent(any))
          .thenAnswer((_) async => Right(null));
      when(mockGetCalendarEvents(any))
          .thenAnswer((_) async => Right(_tEvents));

      final bloc = makeBloc();
      bloc.add(const CalendarEventDeclineRequested(eventId: 'e1'));
      await bloc.stream
          .firstWhere((s) => s is CalendarLoaded || s is CalendarError);
      await bloc.close();

      verify(mockDeclineCalendarEvent(
        const DeclineCalendarEventParams(eventId: 'e1'),
      )).called(1);
      verify(mockGetCalendarEvents(any)).called(1);
    });

    test('propose new time reloads week on success', () async {
      final newStart = DateTime(2026, 6, 15, 10, 0);
      final newEnd = DateTime(2026, 6, 15, 11, 0);

      when(mockProposeNewTime(any))
          .thenAnswer((_) async => Right(null));
      when(mockGetCalendarEvents(any))
          .thenAnswer((_) async => Right(_tEvents));

      final bloc = makeBloc();
      bloc.add(CalendarEventNewTimeProposed(
        eventId: 'e1',
        newStart: newStart,
        newEnd: newEnd,
      ));
      await bloc.stream
          .firstWhere((s) => s is CalendarLoaded || s is CalendarError);
      await bloc.close();

      verify(mockProposeNewTime(any)).called(1);
      verify(mockGetCalendarEvents(any)).called(1);
    });
  });

  group('CalendarBloc cache-first loading', () {
    final cached = <CalendarEvent>[
      CalendarEvent(
        id: 'cached-1',
        subject: 'From cache',
        start: DateTime.utc(2026, 6, 10, 11, 0),
        end: DateTime.utc(2026, 6, 10, 12, 0),
        isAllDay: false,
      ),
    ];

    test('shows the cache first, then the fetched week — no spinner', () async {
      when(mockGetCachedCalendarEvents(any))
          .thenAnswer((_) async => Right(cached));
      when(mockGetCalendarEvents(any)).thenAnswer((_) async => Right(_tEvents));

      final bloc = makeBloc();
      final states = <CalendarState>[];
      final sub = bloc.stream.listen(states.add);

      bloc.add(CalendarWeekLoadRequested(weekStart: _tMonday));
      await bloc.stream.firstWhere(
          (s) => s is CalendarLoaded && !s.isSyncing || s is CalendarError);
      await sub.cancel();
      await bloc.close();

      expect(states.whereType<CalendarLoading>(), isEmpty,
          reason: 'a drawn week must not be replaced by a spinner');
      expect(states[0], isA<CalendarLoaded>());
      final first = states[0] as CalendarLoaded;
      expect(first.events, cached);
      expect(first.isSyncing, isTrue);

      final last = states.last as CalendarLoaded;
      expect(last.events, _tEvents);
      expect(last.isSyncing, isFalse);
      expect(last.syncError, isNull);
    });

    test('still spins when the cache has nothing for the week', () async {
      when(mockGetCalendarEvents(any)).thenAnswer((_) async => Right(_tEvents));

      final bloc = makeBloc();
      final states = <CalendarState>[];
      final sub = bloc.stream.listen(states.add);

      bloc.add(CalendarWeekLoadRequested(weekStart: _tMonday));
      await bloc.stream
          .firstWhere((s) => s is CalendarLoaded || s is CalendarError);
      await sub.cancel();
      await bloc.close();

      expect(states[0], isA<CalendarLoading>());
      expect(states[1], isA<CalendarLoaded>());
    });

    test('keeps the cached week visible when the refresh fails', () async {
      when(mockGetCachedCalendarEvents(any))
          .thenAnswer((_) async => Right(cached));
      when(mockGetCalendarEvents(any)).thenAnswer(
        (_) async => const Left(NetworkFailure(message: 'No connection')),
      );

      final bloc = makeBloc();
      bloc.add(CalendarWeekLoadRequested(weekStart: _tMonday));
      final settled = await bloc.stream.firstWhere(
          (s) => s is CalendarError || (s is CalendarLoaded && !s.isSyncing));
      await bloc.close();

      // Not CalendarError: the cached meetings are stale, not wrong, so they
      // stay on screen with the reason reported beside them.
      expect(settled, isA<CalendarLoaded>());
      final loaded = settled as CalendarLoaded;
      expect(loaded.events, cached);
      expect(loaded.syncError, 'No connection');
      expect(loaded.isSyncing, isFalse);
    });

    test('reports an error only when there is no cache to fall back on',
        () async {
      when(mockGetCalendarEvents(any)).thenAnswer(
        (_) async => const Left(NetworkFailure(message: 'No connection')),
      );

      final bloc = makeBloc();
      bloc.add(CalendarWeekLoadRequested(weekStart: _tMonday));
      final settled = await bloc.stream
          .firstWhere((s) => s is CalendarError || s is CalendarLoaded);
      await bloc.close();

      expect(settled, isA<CalendarError>());
    });

    test('drops a selection whose event the refresh removed', () async {
      when(mockGetCachedCalendarEvents(any))
          .thenAnswer((_) async => Right(cached));
      when(mockGetCalendarEvents(any))
          .thenAnswer((_) async => Right(<CalendarEvent>[]));

      final bloc = makeBloc();
      bloc.add(CalendarWeekLoadRequested(weekStart: _tMonday));
      await bloc.stream.firstWhere((s) => s is CalendarLoaded && s.isSyncing);
      bloc.add(const CalendarEventSelectionToggled(eventId: 'cached-1'));
      await bloc.stream.firstWhere((s) =>
          s is CalendarLoaded && s.selectedEventIds.contains('cached-1'));

      bloc.add(CalendarWeekNavigated(weekStart: _tMonday));
      final after = await bloc.stream
          .firstWhere((s) => s is CalendarLoaded && !s.isSyncing);
      await bloc.close();

      expect((after as CalendarLoaded).selectedEventIds, isEmpty);
    });
  });
}
