import 'package:flutter_test/flutter_test.dart';
import 'package:fpdart/fpdart.dart';
import 'package:mockito/annotations.dart';
import 'package:mockito/mockito.dart';
import 'package:nightmail/core/error/failures.dart';
import 'package:nightmail/domain/entities/calendar_event.dart';
import 'package:nightmail/domain/usecases/cancel_calendar_event.dart';
import 'package:nightmail/domain/usecases/decline_calendar_event.dart';
import 'package:nightmail/domain/usecases/get_calendar_events.dart';
import 'package:nightmail/domain/usecases/propose_new_time.dart';
import 'package:nightmail/domain/usecases/update_calendar_event.dart';
import 'package:nightmail/infrastructure/accounts/account.dart';
import 'package:nightmail/infrastructure/accounts/account_manager.dart';
import 'package:nightmail/infrastructure/notifications/notification_service.dart';
import 'package:nightmail/presentation/blocs/calendar/calendar_bloc.dart';
import 'package:nightmail/presentation/blocs/calendar/calendar_event.dart';
import 'package:nightmail/presentation/blocs/calendar/calendar_state.dart';

import 'calendar_bloc_test.mocks.dart';

// fpdart's Either is not auto-generated by mockito, so register a dummy.
final _emptyRight = Right<Failure, List<CalendarEvent>>([]);
final _voidRight = Right<Failure, void>(null);

final _tMonday = DateTime(2026, 6, 9); // known Monday

final _tEvents = <CalendarEvent>[
  CalendarEvent(
    id: 'e1',
    subject: 'Stand-up',
    start: DateTime.utc(2026, 6, 10, 9, 0),
    end: DateTime.utc(2026, 6, 10, 9, 15),
    isAllDay: false,
  ),
];

@GenerateMocks([
  GetCalendarEvents,
  CancelCalendarEvent,
  DeclineCalendarEvent,
  ProposeNewTime,
  UpdateCalendarEvent,
  NotificationService,
  AccountManager,
])
void main() {
  late MockGetCalendarEvents mockGetCalendarEvents;
  late MockCancelCalendarEvent mockCancelCalendarEvent;
  late MockDeclineCalendarEvent mockDeclineCalendarEvent;
  late MockProposeNewTime mockProposeNewTime;
  late MockUpdateCalendarEvent mockUpdateCalendarEvent;
  late MockNotificationService mockNotificationService;
  late MockAccountManager mockAccountManager;

  CalendarBloc makeBloc() => CalendarBloc(
        getCalendarEvents: mockGetCalendarEvents,
        cancelCalendarEvent: mockCancelCalendarEvent,
        declineCalendarEvent: mockDeclineCalendarEvent,
        proposeNewTime: mockProposeNewTime,
        updateCalendarEvent: mockUpdateCalendarEvent,
        notificationService: mockNotificationService,
        accountManager: mockAccountManager,
      );

  setUp(() {
    mockGetCalendarEvents = MockGetCalendarEvents();
    mockCancelCalendarEvent = MockCancelCalendarEvent();
    mockDeclineCalendarEvent = MockDeclineCalendarEvent();
    mockProposeNewTime = MockProposeNewTime();
    mockUpdateCalendarEvent = MockUpdateCalendarEvent();
    mockNotificationService = MockNotificationService();
    mockAccountManager = MockAccountManager();
    when(mockAccountManager.activeAccount).thenReturn(const GmailAccount(
      id: 'acct1',
      displayName: 'Test',
      emailAddress: 'test@example.com',
    ));
    when(mockNotificationService.cancelEventReminder(
      accountId: anyNamed('accountId'),
      eventId: anyNamed('eventId'),
    )).thenAnswer((_) async {});
    when(mockNotificationService.scheduleEventReminder(
      accountId: anyNamed('accountId'),
      eventId: anyNamed('eventId'),
      eventTitle: anyNamed('eventTitle'),
      startUtc: anyNamed('startUtc'),
      reminderMinutes: anyNamed('reminderMinutes'),
      startIso: anyNamed('startIso'),
    )).thenAnswer((_) async {});
    provideDummy<Either<Failure, List<CalendarEvent>>>(_emptyRight);
    provideDummy<Either<Failure, void>>(_voidRight);
  });

  group('CalendarBloc', () {
    test('initial state has weekStart set to current Monday', () {
      final bloc = makeBloc();
      expect(bloc.state, isA<CalendarInitial>());
      expect(bloc.state.weekStart.weekday, 1);
      bloc.close();
    });

    test('emits [CalendarLoading, CalendarLoaded] on successful fetch',
        () async {
      when(mockGetCalendarEvents(any))
          .thenAnswer((_) async => Right(_tEvents));

      final bloc = makeBloc();
      final states = <CalendarState>[];
      final sub = bloc.stream.listen(states.add);

      bloc.add(CalendarWeekLoadRequested(weekStart: _tMonday));
      await bloc.stream
          .firstWhere((s) => s is CalendarLoaded || s is CalendarError);
      await sub.cancel();
      await bloc.close();

      expect(states[0], isA<CalendarLoading>());
      expect(states[0].weekStart, _tMonday);
      expect(states[1], isA<CalendarLoaded>());
      expect((states[1] as CalendarLoaded).events.length, 1);
    });

    test('emits [CalendarLoading, CalendarError] on failure', () async {
      when(mockGetCalendarEvents(any)).thenAnswer(
        (_) async =>
            const Left(ServerFailure(message: 'Calendar unavailable')),
      );

      final bloc = makeBloc();
      final states = <CalendarState>[];
      final sub = bloc.stream.listen(states.add);

      bloc.add(CalendarWeekLoadRequested(weekStart: _tMonday));
      await bloc.stream
          .firstWhere((s) => s is CalendarLoaded || s is CalendarError);
      await sub.cancel();
      await bloc.close();

      expect(states[0], isA<CalendarLoading>());
      expect(states[1], isA<CalendarError>());
      expect((states[1] as CalendarError).message, 'Calendar unavailable');
    });

    test('emits [CalendarLoading, CalendarLoaded] on week navigation',
        () async {
      when(mockGetCalendarEvents(any))
          .thenAnswer((_) async => Right(_tEvents));

      final bloc = makeBloc();
      final states = <CalendarState>[];
      final sub = bloc.stream.listen(states.add);

      bloc.add(CalendarWeekNavigated(weekStart: _tMonday));
      await bloc.stream
          .firstWhere((s) => s is CalendarLoaded || s is CalendarError);
      await sub.cancel();
      await bloc.close();

      expect(states[0], isA<CalendarLoading>());
      expect(states[1], isA<CalendarLoaded>());
      expect((states[1] as CalendarLoaded).events, _tEvents);
    });

    test('passes a 7-day UTC date range to use case', () async {
      when(mockGetCalendarEvents(any))
          .thenAnswer((_) async => Right(_tEvents));

      final bloc = makeBloc();
      bloc.add(CalendarWeekLoadRequested(weekStart: _tMonday));
      await bloc.stream
          .firstWhere((s) => s is CalendarLoaded || s is CalendarError);
      await bloc.close();

      final captured =
          verify(mockGetCalendarEvents(captureAny)).captured;
      final params = captured.first as GetCalendarEventsParams;
      expect(params.startDateTime.isUtc, isTrue);
      expect(params.endDateTime.difference(params.startDateTime).inDays, 7);
    });

    test('cancel reloads week on success', () async {
      when(mockCancelCalendarEvent(any))
          .thenAnswer((_) async => Right(null));
      when(mockGetCalendarEvents(any))
          .thenAnswer((_) async => Right(_tEvents));

      final bloc = makeBloc();
      bloc.add(const CalendarEventCancelRequested(eventId: 'e1'));
      await bloc.stream
          .firstWhere((s) => s is CalendarLoaded || s is CalendarError);
      await bloc.close();

      verify(mockCancelCalendarEvent(
        const CancelCalendarEventParams(eventId: 'e1'),
      )).called(1);
      verify(mockGetCalendarEvents(any)).called(1);
    });

    test('decline reloads week on success', () async {
      when(mockDeclineCalendarEvent(any))
          .thenAnswer((_) async => Right(null));
      when(mockGetCalendarEvents(any))
          .thenAnswer((_) async => Right(_tEvents));

      final bloc = makeBloc();
      bloc.add(const CalendarEventDeclineRequested(eventId: 'e1'));
      await bloc.stream
          .firstWhere((s) => s is CalendarLoaded || s is CalendarError);
      await bloc.close();

      verify(mockDeclineCalendarEvent(
        const DeclineCalendarEventParams(eventId: 'e1'),
      )).called(1);
      verify(mockGetCalendarEvents(any)).called(1);
    });

    test('propose new time reloads week on success', () async {
      final newStart = DateTime(2026, 6, 15, 10, 0);
      final newEnd = DateTime(2026, 6, 15, 11, 0);

      when(mockProposeNewTime(any))
          .thenAnswer((_) async => Right(null));
      when(mockGetCalendarEvents(any))
          .thenAnswer((_) async => Right(_tEvents));

      final bloc = makeBloc();
      bloc.add(CalendarEventNewTimeProposed(
        eventId: 'e1',
        newStart: newStart,
        newEnd: newEnd,
      ));
      await bloc.stream
          .firstWhere((s) => s is CalendarLoaded || s is CalendarError);
      await bloc.close();

      verify(mockProposeNewTime(any)).called(1);
      verify(mockGetCalendarEvents(any)).called(1);
    });
  });
}
