// Mocks generated by Mockito 5.4.6 from annotations
// in nightmail/test/presentation/blocs/mail_poller_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i11;
import 'dart:typed_data' as _i20;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i12;
import 'package:nightmail/core/settings/app_settings.dart' as _i13;
import 'package:nightmail/data/datasources/local/delta_token_datasource.dart'
    as _i15;
import 'package:nightmail/data/datasources/remote/email_remote_datasource.dart'
    as _i2;
import 'package:nightmail/data/datasources/remote/graph_api_datasource_impl.dart'
    as _i16;
import 'package:nightmail/data/models/calendar_event_model.dart' as _i5;
import 'package:nightmail/data/models/email_folder_model.dart' as _i17;
import 'package:nightmail/data/models/email_model.dart' as _i4;
import 'package:nightmail/data/models/mail_delta_result.dart' as _i8;
import 'package:nightmail/data/models/todo_task_attachment_model.dart' as _i7;
import 'package:nightmail/data/models/todo_task_list_model.dart' as _i21;
import 'package:nightmail/data/models/todo_task_model.dart' as _i6;
import 'package:nightmail/domain/entities/todo_task.dart' as _i22;
import 'package:nightmail/domain/usecases/create_calendar_event.dart' as _i18;
import 'package:nightmail/domain/usecases/update_calendar_event.dart' as _i19;
import 'package:nightmail/infrastructure/accounts/account.dart' as _i10;
import 'package:nightmail/infrastructure/accounts/account_manager.dart' as _i9;
import 'package:nightmail/infrastructure/auth/auth_service.dart' as _i3;
import 'package:nightmail/infrastructure/badge/badge_service.dart' as _i14;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEmailRemoteDatasource_0 extends _i1.SmartFake
    implements _i2.EmailRemoteDatasource {
  _FakeEmailRemoteDatasource_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthService_1 extends _i1.SmartFake implements _i3.AuthService {
  _FakeAuthService_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEmailModel_2 extends _i1.SmartFake implements _i4.EmailModel {
  _FakeEmailModel_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCalendarEventModel_3 extends _i1.SmartFake
    implements _i5.CalendarEventModel {
  _FakeCalendarEventModel_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTodoTaskModel_4 extends _i1.SmartFake implements _i6.TodoTaskModel {
  _FakeTodoTaskModel_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTodoTaskAttachmentModel_5 extends _i1.SmartFake
    implements _i7.TodoTaskAttachmentModel {
  _FakeTodoTaskAttachmentModel_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMailDeltaResult_6 extends _i1.SmartFake
    implements _i8.MailDeltaResult {
  _FakeMailDeltaResult_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AccountManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockAccountManager extends _i1.Mock implements _i9.AccountManager {
  MockAccountManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i10.Account> get accounts =>
      (super.noSuchMethod(
            Invocation.getter(#accounts),
            returnValue: <_i10.Account>[],
          )
          as List<_i10.Account>);

  @override
  bool get hasAccounts =>
      (super.noSuchMethod(Invocation.getter(#hasAccounts), returnValue: false)
          as bool);

  @override
  int get activeIndex =>
      (super.noSuchMethod(Invocation.getter(#activeIndex), returnValue: 0)
          as int);

  @override
  _i2.EmailRemoteDatasource get emailDatasource =>
      (super.noSuchMethod(
            Invocation.getter(#emailDatasource),
            returnValue: _FakeEmailRemoteDatasource_0(
              this,
              Invocation.getter(#emailDatasource),
            ),
          )
          as _i2.EmailRemoteDatasource);

  @override
  _i3.AuthService get activeAuthService =>
      (super.noSuchMethod(
            Invocation.getter(#activeAuthService),
            returnValue: _FakeAuthService_1(
              this,
              Invocation.getter(#activeAuthService),
            ),
          )
          as _i3.AuthService);

  @override
  _i11.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> addAccount(_i10.Account? account) =>
      (super.noSuchMethod(
            Invocation.method(#addAccount, [account]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> updateAccount(_i10.Account? updatedAccount) =>
      (super.noSuchMethod(
            Invocation.method(#updateAccount, [updatedAccount]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<_i10.Account> cycleToNextAccount() =>
      (super.noSuchMethod(
            Invocation.method(#cycleToNextAccount, []),
            returnValue: _i11.Future<_i10.Account>.value(
              _i12.dummyValue<_i10.Account>(
                this,
                Invocation.method(#cycleToNextAccount, []),
              ),
            ),
          )
          as _i11.Future<_i10.Account>);

  @override
  _i11.Future<void> switchToAccount(int? index) =>
      (super.noSuchMethod(
            Invocation.method(#switchToAccount, [index]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> removeAccount(String? accountId) =>
      (super.noSuchMethod(
            Invocation.method(#removeAccount, [accountId]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<Set<String>> getUnauthenticatedAccountIds() =>
      (super.noSuchMethod(
            Invocation.method(#getUnauthenticatedAccountIds, []),
            returnValue: _i11.Future<Set<String>>.value(<String>{}),
          )
          as _i11.Future<Set<String>>);

  @override
  _i11.Future<void> signOutAccount(String? accountId) =>
      (super.noSuchMethod(
            Invocation.method(#signOutAccount, [accountId]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> reauthenticateActiveOAuth() =>
      (super.noSuchMethod(
            Invocation.method(#reauthenticateActiveOAuth, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> reauthenticateImapAccount(
    String? accountId,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#reauthenticateImapAccount, [
              accountId,
              password,
            ]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i2.EmailRemoteDatasource buildEmailDatasourceForAccount(
    _i10.Account? account,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#buildEmailDatasourceForAccount, [account]),
            returnValue: _FakeEmailRemoteDatasource_0(
              this,
              Invocation.method(#buildEmailDatasourceForAccount, [account]),
            ),
          )
          as _i2.EmailRemoteDatasource);
}

/// A class which mocks [AppSettings].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppSettings extends _i1.Mock implements _i13.AppSettings {
  MockAppSettings() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.Future<int> loadPollIntervalSeconds() =>
      (super.noSuchMethod(
            Invocation.method(#loadPollIntervalSeconds, []),
            returnValue: _i11.Future<int>.value(0),
          )
          as _i11.Future<int>);

  @override
  _i11.Future<void> savePollIntervalSeconds(int? seconds) =>
      (super.noSuchMethod(
            Invocation.method(#savePollIntervalSeconds, [seconds]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<bool> loadConfirmDeleteEmail() =>
      (super.noSuchMethod(
            Invocation.method(#loadConfirmDeleteEmail, []),
            returnValue: _i11.Future<bool>.value(false),
          )
          as _i11.Future<bool>);

  @override
  _i11.Future<void> saveConfirmDeleteEmail(bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#saveConfirmDeleteEmail, [value]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<Set<String>> loadExternalImageDomains() =>
      (super.noSuchMethod(
            Invocation.method(#loadExternalImageDomains, []),
            returnValue: _i11.Future<Set<String>>.value(<String>{}),
          )
          as _i11.Future<Set<String>>);

  @override
  _i11.Future<void> saveExternalImageDomain(String? domain) =>
      (super.noSuchMethod(
            Invocation.method(#saveExternalImageDomain, [domain]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> removeExternalImageDomains(Set<String>? toRemove) =>
      (super.noSuchMethod(
            Invocation.method(#removeExternalImageDomains, [toRemove]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);
}

/// A class which mocks [BadgeService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBadgeService extends _i1.Mock implements _i14.BadgeService {
  MockBadgeService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.Future<void> setBadgeCount(int? count) =>
      (super.noSuchMethod(
            Invocation.method(#setBadgeCount, [count]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);
}

/// A class which mocks [DeltaTokenDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeltaTokenDatasource extends _i1.Mock
    implements _i15.DeltaTokenDatasource {
  MockDeltaTokenDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.Future<String?> loadDeltaToken(String? accountId, String? folderId) =>
      (super.noSuchMethod(
            Invocation.method(#loadDeltaToken, [accountId, folderId]),
            returnValue: _i11.Future<String?>.value(),
          )
          as _i11.Future<String?>);

  @override
  _i11.Future<void> saveDeltaToken(
    String? accountId,
    String? folderId,
    String? deltaLink,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveDeltaToken, [
              accountId,
              folderId,
              deltaLink,
            ]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> clearDeltaTokensForAccount(String? accountId) =>
      (super.noSuchMethod(
            Invocation.method(#clearDeltaTokensForAccount, [accountId]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);
}

/// A class which mocks [GraphApiDatasourceImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockGraphApiDatasourceImpl extends _i1.Mock
    implements _i16.GraphApiDatasourceImpl {
  MockGraphApiDatasourceImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.Future<List<_i4.EmailModel>> getEmails({
    String? folderId,
    int? top = 25,
    int? skip = 0,
    String? filter,
    String? orderBy = 'receivedDateTime desc',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getEmails, [], {
              #folderId: folderId,
              #top: top,
              #skip: skip,
              #filter: filter,
              #orderBy: orderBy,
            }),
            returnValue: _i11.Future<List<_i4.EmailModel>>.value(
              <_i4.EmailModel>[],
            ),
          )
          as _i11.Future<List<_i4.EmailModel>>);

  @override
  _i11.Future<_i4.EmailModel> getEmail(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getEmail, [id]),
            returnValue: _i11.Future<_i4.EmailModel>.value(
              _FakeEmailModel_2(this, Invocation.method(#getEmail, [id])),
            ),
          )
          as _i11.Future<_i4.EmailModel>);

  @override
  _i11.Future<_i4.EmailModel> updateEmailReadStatus({
    required String? id,
    required bool? isRead,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateEmailReadStatus, [], {
              #id: id,
              #isRead: isRead,
            }),
            returnValue: _i11.Future<_i4.EmailModel>.value(
              _FakeEmailModel_2(
                this,
                Invocation.method(#updateEmailReadStatus, [], {
                  #id: id,
                  #isRead: isRead,
                }),
              ),
            ),
          )
          as _i11.Future<_i4.EmailModel>);

  @override
  _i11.Future<List<_i17.EmailFolderModel>> getMailFolders() =>
      (super.noSuchMethod(
            Invocation.method(#getMailFolders, []),
            returnValue: _i11.Future<List<_i17.EmailFolderModel>>.value(
              <_i17.EmailFolderModel>[],
            ),
          )
          as _i11.Future<List<_i17.EmailFolderModel>>);

  @override
  _i11.Future<List<_i17.EmailFolderModel>> getChildFolders(
    String? parentFolderId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getChildFolders, [parentFolderId]),
            returnValue: _i11.Future<List<_i17.EmailFolderModel>>.value(
              <_i17.EmailFolderModel>[],
            ),
          )
          as _i11.Future<List<_i17.EmailFolderModel>>);

  @override
  _i11.Future<List<_i5.CalendarEventModel>> getCalendarEvents({
    required DateTime? startDateTime,
    required DateTime? endDateTime,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getCalendarEvents, [], {
              #startDateTime: startDateTime,
              #endDateTime: endDateTime,
            }),
            returnValue: _i11.Future<List<_i5.CalendarEventModel>>.value(
              <_i5.CalendarEventModel>[],
            ),
          )
          as _i11.Future<List<_i5.CalendarEventModel>>);

  @override
  _i11.Future<_i5.CalendarEventModel> createCalendarEvent({
    required _i18.CreateCalendarEventParams? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createCalendarEvent, [], {#params: params}),
            returnValue: _i11.Future<_i5.CalendarEventModel>.value(
              _FakeCalendarEventModel_3(
                this,
                Invocation.method(#createCalendarEvent, [], {#params: params}),
              ),
            ),
          )
          as _i11.Future<_i5.CalendarEventModel>);

  @override
  _i11.Future<_i5.CalendarEventModel> updateCalendarEvent({
    required _i19.UpdateCalendarEventParams? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateCalendarEvent, [], {#params: params}),
            returnValue: _i11.Future<_i5.CalendarEventModel>.value(
              _FakeCalendarEventModel_3(
                this,
                Invocation.method(#updateCalendarEvent, [], {#params: params}),
              ),
            ),
          )
          as _i11.Future<_i5.CalendarEventModel>);

  @override
  _i11.Future<void> sendEmail({
    required List<String>? toAddresses,
    List<String>? ccAddresses = const [],
    required String? subject,
    required String? body,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendEmail, [], {
              #toAddresses: toAddresses,
              #ccAddresses: ccAddresses,
              #subject: subject,
              #body: body,
            }),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> replyToEmail({
    required String? messageId,
    required String? comment,
    bool? replyAll = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#replyToEmail, [], {
              #messageId: messageId,
              #comment: comment,
              #replyAll: replyAll,
            }),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> forwardEmail({
    required String? messageId,
    required List<String>? toAddresses,
    required String? comment,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#forwardEmail, [], {
              #messageId: messageId,
              #toAddresses: toAddresses,
              #comment: comment,
            }),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> moveEmail(String? id, String? destinationFolderId) =>
      (super.noSuchMethod(
            Invocation.method(#moveEmail, [id, destinationFolderId]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> deleteEmail(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteEmail, [id]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> emptyFolder(
    String? folderId, {
    bool? permanentDelete = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #emptyFolder,
              [folderId],
              {#permanentDelete: permanentDelete},
            ),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<_i20.Uint8List> downloadAttachment(
    String? messageId,
    String? attachmentId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#downloadAttachment, [messageId, attachmentId]),
            returnValue: _i11.Future<_i20.Uint8List>.value(_i20.Uint8List(0)),
          )
          as _i11.Future<_i20.Uint8List>);

  @override
  _i11.Future<List<_i21.TodoTaskListModel>> getTaskLists() =>
      (super.noSuchMethod(
            Invocation.method(#getTaskLists, []),
            returnValue: _i11.Future<List<_i21.TodoTaskListModel>>.value(
              <_i21.TodoTaskListModel>[],
            ),
          )
          as _i11.Future<List<_i21.TodoTaskListModel>>);

  @override
  _i11.Future<List<_i6.TodoTaskModel>> getTasks(
    String? listId, {
    bool? includeCompleted = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getTasks,
              [listId],
              {#includeCompleted: includeCompleted},
            ),
            returnValue: _i11.Future<List<_i6.TodoTaskModel>>.value(
              <_i6.TodoTaskModel>[],
            ),
          )
          as _i11.Future<List<_i6.TodoTaskModel>>);

  @override
  _i11.Future<_i6.TodoTaskModel> createTask({
    required String? listId,
    required String? title,
    String? body,
    DateTime? dueDate,
    _i22.TodoTaskImportance? importance = _i22.TodoTaskImportance.normal,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createTask, [], {
              #listId: listId,
              #title: title,
              #body: body,
              #dueDate: dueDate,
              #importance: importance,
            }),
            returnValue: _i11.Future<_i6.TodoTaskModel>.value(
              _FakeTodoTaskModel_4(
                this,
                Invocation.method(#createTask, [], {
                  #listId: listId,
                  #title: title,
                  #body: body,
                  #dueDate: dueDate,
                  #importance: importance,
                }),
              ),
            ),
          )
          as _i11.Future<_i6.TodoTaskModel>);

  @override
  _i11.Future<_i6.TodoTaskModel> updateTaskStatus({
    required String? listId,
    required String? taskId,
    required _i22.TodoTaskStatus? status,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateTaskStatus, [], {
              #listId: listId,
              #taskId: taskId,
              #status: status,
            }),
            returnValue: _i11.Future<_i6.TodoTaskModel>.value(
              _FakeTodoTaskModel_4(
                this,
                Invocation.method(#updateTaskStatus, [], {
                  #listId: listId,
                  #taskId: taskId,
                  #status: status,
                }),
              ),
            ),
          )
          as _i11.Future<_i6.TodoTaskModel>);

  @override
  _i11.Future<_i6.TodoTaskModel> updateTaskDueDate({
    required String? listId,
    required String? taskId,
    required DateTime? dueDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateTaskDueDate, [], {
              #listId: listId,
              #taskId: taskId,
              #dueDate: dueDate,
            }),
            returnValue: _i11.Future<_i6.TodoTaskModel>.value(
              _FakeTodoTaskModel_4(
                this,
                Invocation.method(#updateTaskDueDate, [], {
                  #listId: listId,
                  #taskId: taskId,
                  #dueDate: dueDate,
                }),
              ),
            ),
          )
          as _i11.Future<_i6.TodoTaskModel>);

  @override
  _i11.Future<_i20.Uint8List> getRawEmailBytes(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getRawEmailBytes, [id]),
            returnValue: _i11.Future<_i20.Uint8List>.value(_i20.Uint8List(0)),
          )
          as _i11.Future<_i20.Uint8List>);

  @override
  _i11.Future<_i7.TodoTaskAttachmentModel> attachEmailToTask({
    required String? listId,
    required String? taskId,
    required String? fileName,
    required _i20.Uint8List? emlBytes,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#attachEmailToTask, [], {
              #listId: listId,
              #taskId: taskId,
              #fileName: fileName,
              #emlBytes: emlBytes,
            }),
            returnValue: _i11.Future<_i7.TodoTaskAttachmentModel>.value(
              _FakeTodoTaskAttachmentModel_5(
                this,
                Invocation.method(#attachEmailToTask, [], {
                  #listId: listId,
                  #taskId: taskId,
                  #fileName: fileName,
                  #emlBytes: emlBytes,
                }),
              ),
            ),
          )
          as _i11.Future<_i7.TodoTaskAttachmentModel>);

  @override
  _i11.Future<List<_i7.TodoTaskAttachmentModel>> getTaskAttachments({
    required String? listId,
    required String? taskId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getTaskAttachments, [], {
              #listId: listId,
              #taskId: taskId,
            }),
            returnValue: _i11.Future<List<_i7.TodoTaskAttachmentModel>>.value(
              <_i7.TodoTaskAttachmentModel>[],
            ),
          )
          as _i11.Future<List<_i7.TodoTaskAttachmentModel>>);

  @override
  _i11.Future<_i20.Uint8List> downloadTaskAttachment({
    required String? listId,
    required String? taskId,
    required String? attachmentId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#downloadTaskAttachment, [], {
              #listId: listId,
              #taskId: taskId,
              #attachmentId: attachmentId,
            }),
            returnValue: _i11.Future<_i20.Uint8List>.value(_i20.Uint8List(0)),
          )
          as _i11.Future<_i20.Uint8List>);

  @override
  _i11.Future<_i8.MailDeltaResult> syncMailDelta(
    String? folderId, {
    String? deltaLink,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #syncMailDelta,
              [folderId],
              {#deltaLink: deltaLink},
            ),
            returnValue: _i11.Future<_i8.MailDeltaResult>.value(
              _FakeMailDeltaResult_6(
                this,
                Invocation.method(
                  #syncMailDelta,
                  [folderId],
                  {#deltaLink: deltaLink},
                ),
              ),
            ),
          )
          as _i11.Future<_i8.MailDeltaResult>);
}

/// A class which mocks [EmailRemoteDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockEmailRemoteDatasource extends _i1.Mock
    implements _i2.EmailRemoteDatasource {
  MockEmailRemoteDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.Future<List<_i4.EmailModel>> getEmails({
    String? folderId,
    int? top = 25,
    int? skip = 0,
    String? filter,
    String? orderBy = 'receivedDateTime desc',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getEmails, [], {
              #folderId: folderId,
              #top: top,
              #skip: skip,
              #filter: filter,
              #orderBy: orderBy,
            }),
            returnValue: _i11.Future<List<_i4.EmailModel>>.value(
              <_i4.EmailModel>[],
            ),
          )
          as _i11.Future<List<_i4.EmailModel>>);

  @override
  _i11.Future<_i4.EmailModel> getEmail(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getEmail, [id]),
            returnValue: _i11.Future<_i4.EmailModel>.value(
              _FakeEmailModel_2(this, Invocation.method(#getEmail, [id])),
            ),
          )
          as _i11.Future<_i4.EmailModel>);

  @override
  _i11.Future<_i4.EmailModel> updateEmailReadStatus({
    required String? id,
    required bool? isRead,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateEmailReadStatus, [], {
              #id: id,
              #isRead: isRead,
            }),
            returnValue: _i11.Future<_i4.EmailModel>.value(
              _FakeEmailModel_2(
                this,
                Invocation.method(#updateEmailReadStatus, [], {
                  #id: id,
                  #isRead: isRead,
                }),
              ),
            ),
          )
          as _i11.Future<_i4.EmailModel>);

  @override
  _i11.Future<List<_i17.EmailFolderModel>> getMailFolders() =>
      (super.noSuchMethod(
            Invocation.method(#getMailFolders, []),
            returnValue: _i11.Future<List<_i17.EmailFolderModel>>.value(
              <_i17.EmailFolderModel>[],
            ),
          )
          as _i11.Future<List<_i17.EmailFolderModel>>);

  @override
  _i11.Future<List<_i17.EmailFolderModel>> getChildFolders(
    String? parentFolderId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getChildFolders, [parentFolderId]),
            returnValue: _i11.Future<List<_i17.EmailFolderModel>>.value(
              <_i17.EmailFolderModel>[],
            ),
          )
          as _i11.Future<List<_i17.EmailFolderModel>>);

  @override
  _i11.Future<void> sendEmail({
    required List<String>? toAddresses,
    List<String>? ccAddresses = const [],
    required String? subject,
    required String? body,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendEmail, [], {
              #toAddresses: toAddresses,
              #ccAddresses: ccAddresses,
              #subject: subject,
              #body: body,
            }),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> replyToEmail({
    required String? messageId,
    required String? comment,
    bool? replyAll = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#replyToEmail, [], {
              #messageId: messageId,
              #comment: comment,
              #replyAll: replyAll,
            }),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> forwardEmail({
    required String? messageId,
    required List<String>? toAddresses,
    required String? comment,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#forwardEmail, [], {
              #messageId: messageId,
              #toAddresses: toAddresses,
              #comment: comment,
            }),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> moveEmail(String? id, String? destinationFolderId) =>
      (super.noSuchMethod(
            Invocation.method(#moveEmail, [id, destinationFolderId]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> deleteEmail(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteEmail, [id]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> emptyFolder(
    String? folderId, {
    bool? permanentDelete = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #emptyFolder,
              [folderId],
              {#permanentDelete: permanentDelete},
            ),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<_i20.Uint8List> downloadAttachment(
    String? messageId,
    String? attachmentId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#downloadAttachment, [messageId, attachmentId]),
            returnValue: _i11.Future<_i20.Uint8List>.value(_i20.Uint8List(0)),
          )
          as _i11.Future<_i20.Uint8List>);

  @override
  _i11.Future<_i20.Uint8List> getRawEmailBytes(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getRawEmailBytes, [id]),
            returnValue: _i11.Future<_i20.Uint8List>.value(_i20.Uint8List(0)),
          )
          as _i11.Future<_i20.Uint8List>);
}
