// Mocks generated by Mockito 5.4.6 from annotations
// in nightmail/test/data/repositories/calendar_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:nightmail/data/datasources/remote/calendar_remote_datasource.dart'
    as _i9;
import 'package:nightmail/data/datasources/remote/email_remote_datasource.dart'
    as _i2;
import 'package:nightmail/data/models/calendar_event_model.dart' as _i4;
import 'package:nightmail/domain/usecases/create_calendar_event.dart' as _i10;
import 'package:nightmail/domain/usecases/update_calendar_event.dart' as _i11;
import 'package:nightmail/infrastructure/accounts/account.dart' as _i6;
import 'package:nightmail/infrastructure/accounts/account_manager.dart' as _i5;
import 'package:nightmail/infrastructure/auth/auth_service.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEmailRemoteDatasource_0 extends _i1.SmartFake
    implements _i2.EmailRemoteDatasource {
  _FakeEmailRemoteDatasource_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthService_1 extends _i1.SmartFake implements _i3.AuthService {
  _FakeAuthService_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCalendarEventModel_2 extends _i1.SmartFake
    implements _i4.CalendarEventModel {
  _FakeCalendarEventModel_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AccountManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockAccountManager extends _i1.Mock implements _i5.AccountManager {
  MockAccountManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i6.Account> get accounts =>
      (super.noSuchMethod(
            Invocation.getter(#accounts),
            returnValue: <_i6.Account>[],
          )
          as List<_i6.Account>);

  @override
  bool get hasAccounts =>
      (super.noSuchMethod(Invocation.getter(#hasAccounts), returnValue: false)
          as bool);

  @override
  int get activeIndex =>
      (super.noSuchMethod(Invocation.getter(#activeIndex), returnValue: 0)
          as int);

  @override
  _i2.EmailRemoteDatasource get emailDatasource =>
      (super.noSuchMethod(
            Invocation.getter(#emailDatasource),
            returnValue: _FakeEmailRemoteDatasource_0(
              this,
              Invocation.getter(#emailDatasource),
            ),
          )
          as _i2.EmailRemoteDatasource);

  @override
  _i3.AuthService get activeAuthService =>
      (super.noSuchMethod(
            Invocation.getter(#activeAuthService),
            returnValue: _FakeAuthService_1(
              this,
              Invocation.getter(#activeAuthService),
            ),
          )
          as _i3.AuthService);

  @override
  _i7.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> addAccount(_i6.Account? account) =>
      (super.noSuchMethod(
            Invocation.method(#addAccount, [account]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> updateAccount(_i6.Account? updatedAccount) =>
      (super.noSuchMethod(
            Invocation.method(#updateAccount, [updatedAccount]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<_i6.Account> cycleToNextAccount() =>
      (super.noSuchMethod(
            Invocation.method(#cycleToNextAccount, []),
            returnValue: _i7.Future<_i6.Account>.value(
              _i8.dummyValue<_i6.Account>(
                this,
                Invocation.method(#cycleToNextAccount, []),
              ),
            ),
          )
          as _i7.Future<_i6.Account>);

  @override
  _i7.Future<void> switchToAccount(int? index) =>
      (super.noSuchMethod(
            Invocation.method(#switchToAccount, [index]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> removeAccount(String? accountId) =>
      (super.noSuchMethod(
            Invocation.method(#removeAccount, [accountId]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i2.EmailRemoteDatasource buildEmailDatasourceForAccount(
    _i6.Account? account,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#buildEmailDatasourceForAccount, [account]),
            returnValue: _FakeEmailRemoteDatasource_0(
              this,
              Invocation.method(#buildEmailDatasourceForAccount, [account]),
            ),
          )
          as _i2.EmailRemoteDatasource);
}

/// A class which mocks [CalendarRemoteDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockCalendarRemoteDatasource extends _i1.Mock
    implements _i9.CalendarRemoteDatasource {
  MockCalendarRemoteDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<List<_i4.CalendarEventModel>> getCalendarEvents({
    required DateTime? startDateTime,
    required DateTime? endDateTime,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getCalendarEvents, [], {
              #startDateTime: startDateTime,
              #endDateTime: endDateTime,
            }),
            returnValue: _i7.Future<List<_i4.CalendarEventModel>>.value(
              <_i4.CalendarEventModel>[],
            ),
          )
          as _i7.Future<List<_i4.CalendarEventModel>>);

  @override
  _i7.Future<_i4.CalendarEventModel> createCalendarEvent({
    required _i10.CreateCalendarEventParams? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createCalendarEvent, [], {#params: params}),
            returnValue: _i7.Future<_i4.CalendarEventModel>.value(
              _FakeCalendarEventModel_2(
                this,
                Invocation.method(#createCalendarEvent, [], {#params: params}),
              ),
            ),
          )
          as _i7.Future<_i4.CalendarEventModel>);

  @override
  _i7.Future<_i4.CalendarEventModel> updateCalendarEvent({
    required _i11.UpdateCalendarEventParams? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateCalendarEvent, [], {#params: params}),
            returnValue: _i7.Future<_i4.CalendarEventModel>.value(
              _FakeCalendarEventModel_2(
                this,
                Invocation.method(#updateCalendarEvent, [], {#params: params}),
              ),
            ),
          )
          as _i7.Future<_i4.CalendarEventModel>);
}
