// Mocks generated by Mockito 5.4.6 from annotations
// in nightmail/test/data/repositories/email_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:nightmail/data/datasources/remote/graph_api_remote_datasource.dart'
    as _i3;
import 'package:nightmail/data/models/email_folder_model.dart' as _i5;
import 'package:nightmail/data/models/email_model.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEmailModel_0 extends _i1.SmartFake implements _i2.EmailModel {
  _FakeEmailModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GraphApiRemoteDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockGraphApiRemoteDatasource extends _i1.Mock
    implements _i3.GraphApiRemoteDatasource {
  MockGraphApiRemoteDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.EmailModel>> getEmails({
    String? folderId,
    int? top = 25,
    int? skip = 0,
    String? filter,
    String? orderBy = 'receivedDateTime desc',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getEmails, [], {
              #folderId: folderId,
              #top: top,
              #skip: skip,
              #filter: filter,
              #orderBy: orderBy,
            }),
            returnValue: _i4.Future<List<_i2.EmailModel>>.value(
              <_i2.EmailModel>[],
            ),
          )
          as _i4.Future<List<_i2.EmailModel>>);

  @override
  _i4.Future<_i2.EmailModel> getEmail(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getEmail, [id]),
            returnValue: _i4.Future<_i2.EmailModel>.value(
              _FakeEmailModel_0(this, Invocation.method(#getEmail, [id])),
            ),
          )
          as _i4.Future<_i2.EmailModel>);

  @override
  _i4.Future<_i2.EmailModel> updateEmailReadStatus({
    required String? id,
    required bool? isRead,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateEmailReadStatus, [], {
              #id: id,
              #isRead: isRead,
            }),
            returnValue: _i4.Future<_i2.EmailModel>.value(
              _FakeEmailModel_0(
                this,
                Invocation.method(#updateEmailReadStatus, [], {
                  #id: id,
                  #isRead: isRead,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.EmailModel>);

  @override
  _i4.Future<List<_i5.EmailFolderModel>> getMailFolders() =>
      (super.noSuchMethod(
            Invocation.method(#getMailFolders, []),
            returnValue: _i4.Future<List<_i5.EmailFolderModel>>.value(
              <_i5.EmailFolderModel>[],
            ),
          )
          as _i4.Future<List<_i5.EmailFolderModel>>);

  @override
  _i4.Future<List<_i5.EmailFolderModel>> getChildFolders(
    String? parentFolderId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getChildFolders, [parentFolderId]),
            returnValue: _i4.Future<List<_i5.EmailFolderModel>>.value(
              <_i5.EmailFolderModel>[],
            ),
          )
          as _i4.Future<List<_i5.EmailFolderModel>>);
}
