// Mocks generated by Mockito 5.4.6 from annotations
// in nightmail/test/data/repositories/email_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:typed_data' as _i12;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:nightmail/data/datasources/local/email_local_datasource.dart'
    as _i9;
import 'package:nightmail/data/datasources/remote/email_remote_datasource.dart'
    as _i2;
import 'package:nightmail/data/models/email_folder_model.dart' as _i11;
import 'package:nightmail/data/models/email_model.dart' as _i4;
import 'package:nightmail/domain/entities/email.dart' as _i10;
import 'package:nightmail/infrastructure/accounts/account.dart' as _i6;
import 'package:nightmail/infrastructure/accounts/account_manager.dart' as _i5;
import 'package:nightmail/infrastructure/auth/auth_service.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEmailRemoteDatasource_0 extends _i1.SmartFake
    implements _i2.EmailRemoteDatasource {
  _FakeEmailRemoteDatasource_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthService_1 extends _i1.SmartFake implements _i3.AuthService {
  _FakeAuthService_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEmailModel_2 extends _i1.SmartFake implements _i4.EmailModel {
  _FakeEmailModel_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AccountManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockAccountManager extends _i1.Mock implements _i5.AccountManager {
  MockAccountManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i6.Account> get accounts =>
      (super.noSuchMethod(
            Invocation.getter(#accounts),
            returnValue: <_i6.Account>[],
          )
          as List<_i6.Account>);

  @override
  bool get hasAccounts =>
      (super.noSuchMethod(Invocation.getter(#hasAccounts), returnValue: false)
          as bool);

  @override
  int get activeIndex =>
      (super.noSuchMethod(Invocation.getter(#activeIndex), returnValue: 0)
          as int);

  @override
  _i2.EmailRemoteDatasource get emailDatasource =>
      (super.noSuchMethod(
            Invocation.getter(#emailDatasource),
            returnValue: _FakeEmailRemoteDatasource_0(
              this,
              Invocation.getter(#emailDatasource),
            ),
          )
          as _i2.EmailRemoteDatasource);

  @override
  _i3.AuthService get activeAuthService =>
      (super.noSuchMethod(
            Invocation.getter(#activeAuthService),
            returnValue: _FakeAuthService_1(
              this,
              Invocation.getter(#activeAuthService),
            ),
          )
          as _i3.AuthService);

  @override
  _i7.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> addAccount(_i6.Account? account) =>
      (super.noSuchMethod(
            Invocation.method(#addAccount, [account]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> updateAccount(_i6.Account? updatedAccount) =>
      (super.noSuchMethod(
            Invocation.method(#updateAccount, [updatedAccount]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<_i6.Account> cycleToNextAccount() =>
      (super.noSuchMethod(
            Invocation.method(#cycleToNextAccount, []),
            returnValue: _i7.Future<_i6.Account>.value(
              _i8.dummyValue<_i6.Account>(
                this,
                Invocation.method(#cycleToNextAccount, []),
              ),
            ),
          )
          as _i7.Future<_i6.Account>);

  @override
  _i7.Future<void> switchToAccount(int? index) =>
      (super.noSuchMethod(
            Invocation.method(#switchToAccount, [index]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> removeAccount(String? accountId) =>
      (super.noSuchMethod(
            Invocation.method(#removeAccount, [accountId]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i2.EmailRemoteDatasource buildEmailDatasourceForAccount(
    _i6.Account? account,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#buildEmailDatasourceForAccount, [account]),
            returnValue: _FakeEmailRemoteDatasource_0(
              this,
              Invocation.method(#buildEmailDatasourceForAccount, [account]),
            ),
          )
          as _i2.EmailRemoteDatasource);
}

/// A class which mocks [EmailLocalDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockEmailLocalDatasource extends _i1.Mock
    implements _i9.EmailLocalDatasource {
  MockEmailLocalDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<List<_i10.Email>> getCachedEmails({
    required String? accountId,
    required String? folderId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedEmails, [], {
              #accountId: accountId,
              #folderId: folderId,
            }),
            returnValue: _i7.Future<List<_i10.Email>>.value(<_i10.Email>[]),
          )
          as _i7.Future<List<_i10.Email>>);

  @override
  _i7.Future<void> cacheEmails({
    required String? accountId,
    required String? folderId,
    required List<_i10.Email>? emails,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#cacheEmails, [], {
              #accountId: accountId,
              #folderId: folderId,
              #emails: emails,
            }),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> clearCacheForAccount(String? accountId) =>
      (super.noSuchMethod(
            Invocation.method(#clearCacheForAccount, [accountId]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> clearCacheForFolder({
    required String? accountId,
    required String? folderId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#clearCacheForFolder, [], {
              #accountId: accountId,
              #folderId: folderId,
            }),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> deleteEmailFromCache({
    required String? accountId,
    required String? emailId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteEmailFromCache, [], {
              #accountId: accountId,
              #emailId: emailId,
            }),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> updateEmailReadStatusInCache({
    required String? accountId,
    required String? emailId,
    required bool? isRead,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateEmailReadStatusInCache, [], {
              #accountId: accountId,
              #emailId: emailId,
              #isRead: isRead,
            }),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}

/// A class which mocks [EmailRemoteDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockEmailRemoteDatasource extends _i1.Mock
    implements _i2.EmailRemoteDatasource {
  MockEmailRemoteDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<List<_i4.EmailModel>> getEmails({
    String? folderId,
    int? top = 25,
    int? skip = 0,
    String? filter,
    String? orderBy = 'receivedDateTime desc',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getEmails, [], {
              #folderId: folderId,
              #top: top,
              #skip: skip,
              #filter: filter,
              #orderBy: orderBy,
            }),
            returnValue: _i7.Future<List<_i4.EmailModel>>.value(
              <_i4.EmailModel>[],
            ),
          )
          as _i7.Future<List<_i4.EmailModel>>);

  @override
  _i7.Future<_i4.EmailModel> getEmail(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getEmail, [id]),
            returnValue: _i7.Future<_i4.EmailModel>.value(
              _FakeEmailModel_2(this, Invocation.method(#getEmail, [id])),
            ),
          )
          as _i7.Future<_i4.EmailModel>);

  @override
  _i7.Future<_i4.EmailModel> updateEmailReadStatus({
    required String? id,
    required bool? isRead,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateEmailReadStatus, [], {
              #id: id,
              #isRead: isRead,
            }),
            returnValue: _i7.Future<_i4.EmailModel>.value(
              _FakeEmailModel_2(
                this,
                Invocation.method(#updateEmailReadStatus, [], {
                  #id: id,
                  #isRead: isRead,
                }),
              ),
            ),
          )
          as _i7.Future<_i4.EmailModel>);

  @override
  _i7.Future<List<_i11.EmailFolderModel>> getMailFolders() =>
      (super.noSuchMethod(
            Invocation.method(#getMailFolders, []),
            returnValue: _i7.Future<List<_i11.EmailFolderModel>>.value(
              <_i11.EmailFolderModel>[],
            ),
          )
          as _i7.Future<List<_i11.EmailFolderModel>>);

  @override
  _i7.Future<List<_i11.EmailFolderModel>> getChildFolders(
    String? parentFolderId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getChildFolders, [parentFolderId]),
            returnValue: _i7.Future<List<_i11.EmailFolderModel>>.value(
              <_i11.EmailFolderModel>[],
            ),
          )
          as _i7.Future<List<_i11.EmailFolderModel>>);

  @override
  _i7.Future<void> sendEmail({
    required List<String>? toAddresses,
    List<String>? ccAddresses = const [],
    required String? subject,
    required String? body,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendEmail, [], {
              #toAddresses: toAddresses,
              #ccAddresses: ccAddresses,
              #subject: subject,
              #body: body,
            }),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> replyToEmail({
    required String? messageId,
    required String? comment,
    bool? replyAll = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#replyToEmail, [], {
              #messageId: messageId,
              #comment: comment,
              #replyAll: replyAll,
            }),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> forwardEmail({
    required String? messageId,
    required List<String>? toAddresses,
    required String? comment,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#forwardEmail, [], {
              #messageId: messageId,
              #toAddresses: toAddresses,
              #comment: comment,
            }),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> moveEmail(String? id, String? destinationFolderId) =>
      (super.noSuchMethod(
            Invocation.method(#moveEmail, [id, destinationFolderId]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> deleteEmail(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteEmail, [id]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> emptyFolder(
    String? folderId, {
    bool? permanentDelete = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #emptyFolder,
              [folderId],
              {#permanentDelete: permanentDelete},
            ),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<_i12.Uint8List> downloadAttachment(
    String? messageId,
    String? attachmentId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#downloadAttachment, [messageId, attachmentId]),
            returnValue: _i7.Future<_i12.Uint8List>.value(_i12.Uint8List(0)),
          )
          as _i7.Future<_i12.Uint8List>);

  @override
  _i7.Future<_i12.Uint8List> getRawEmailBytes(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getRawEmailBytes, [id]),
            returnValue: _i7.Future<_i12.Uint8List>.value(_i12.Uint8List(0)),
          )
          as _i7.Future<_i12.Uint8List>);
}
