// Mocks generated by Mockito 5.4.6 from annotations
// in nightmail/test/domain/usecases/get_emails_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:fpdart/fpdart.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:nightmail/core/error/failures.dart' as _i5;
import 'package:nightmail/domain/entities/email.dart' as _i6;
import 'package:nightmail/domain/entities/email_folder.dart' as _i8;
import 'package:nightmail/domain/repositories/email_repository.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [EmailRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockEmailRepository extends _i1.Mock implements _i2.EmailRepository {
  MockEmailRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.Failure, List<_i6.Email>>> getEmails({
    String? folderId,
    int? top = 25,
    int? skip = 0,
    String? filter,
    String? orderBy = 'receivedDateTime desc',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getEmails, [], {
              #folderId: folderId,
              #top: top,
              #skip: skip,
              #filter: filter,
              #orderBy: orderBy,
            }),
            returnValue:
                _i3.Future<_i4.Either<_i5.Failure, List<_i6.Email>>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, List<_i6.Email>>>(
                    this,
                    Invocation.method(#getEmails, [], {
                      #folderId: folderId,
                      #top: top,
                      #skip: skip,
                      #filter: filter,
                      #orderBy: orderBy,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, List<_i6.Email>>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i6.Email>> getEmail(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getEmail, [id]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, _i6.Email>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, _i6.Email>>(
                this,
                Invocation.method(#getEmail, [id]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, _i6.Email>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i6.Email>> markAsRead({
    required String? id,
    required bool? isRead,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#markAsRead, [], {#id: id, #isRead: isRead}),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, _i6.Email>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, _i6.Email>>(
                this,
                Invocation.method(#markAsRead, [], {#id: id, #isRead: isRead}),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, _i6.Email>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, List<_i8.EmailFolder>>> getMailFolders() =>
      (super.noSuchMethod(
            Invocation.method(#getMailFolders, []),
            returnValue:
                _i3.Future<
                  _i4.Either<_i5.Failure, List<_i8.EmailFolder>>
                >.value(
                  _i7.dummyValue<
                    _i4.Either<_i5.Failure, List<_i8.EmailFolder>>
                  >(this, Invocation.method(#getMailFolders, [])),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, List<_i8.EmailFolder>>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, List<_i8.EmailFolder>>> getChildFolders(
    String? parentFolderId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getChildFolders, [parentFolderId]),
            returnValue:
                _i3.Future<
                  _i4.Either<_i5.Failure, List<_i8.EmailFolder>>
                >.value(
                  _i7.dummyValue<
                    _i4.Either<_i5.Failure, List<_i8.EmailFolder>>
                  >(
                    this,
                    Invocation.method(#getChildFolders, [parentFolderId]),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, List<_i8.EmailFolder>>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i4.Unit>> sendEmail({
    required List<String>? toAddresses,
    List<String>? ccAddresses = const [],
    required String? subject,
    required String? body,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendEmail, [], {
              #toAddresses: toAddresses,
              #ccAddresses: ccAddresses,
              #subject: subject,
              #body: body,
            }),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, _i4.Unit>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, _i4.Unit>>(
                this,
                Invocation.method(#sendEmail, [], {
                  #toAddresses: toAddresses,
                  #ccAddresses: ccAddresses,
                  #subject: subject,
                  #body: body,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, _i4.Unit>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i4.Unit>> replyToEmail({
    required String? messageId,
    required String? comment,
    bool? replyAll = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#replyToEmail, [], {
              #messageId: messageId,
              #comment: comment,
              #replyAll: replyAll,
            }),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, _i4.Unit>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, _i4.Unit>>(
                this,
                Invocation.method(#replyToEmail, [], {
                  #messageId: messageId,
                  #comment: comment,
                  #replyAll: replyAll,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, _i4.Unit>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i4.Unit>> forwardEmail({
    required String? messageId,
    required List<String>? toAddresses,
    required String? comment,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#forwardEmail, [], {
              #messageId: messageId,
              #toAddresses: toAddresses,
              #comment: comment,
            }),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, _i4.Unit>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, _i4.Unit>>(
                this,
                Invocation.method(#forwardEmail, [], {
                  #messageId: messageId,
                  #toAddresses: toAddresses,
                  #comment: comment,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, _i4.Unit>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i4.Unit>> deleteEmail(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteEmail, [id]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, _i4.Unit>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, _i4.Unit>>(
                this,
                Invocation.method(#deleteEmail, [id]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, _i4.Unit>>);
}
