name: nightmail
base: core24
version: 'dev'
summary: A cross-platform email client for Office 365
description: |
  NightMail is a cross-platform email client for Office 365 via the
  Microsoft Graph API.
grade: stable
confinement: classic

apps:
  nightmail:
    command: nightmail

parts:
  nightmail:
    plugin: dump
    source: build/linux/x64/release/bundle
